//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string contrasena { get; set; }
        public string correo { get; set; }
        public string userRole { get; set; }
        public Nullable<System.DateTime> lastLogindate { get; set; }
        public Nullable<System.DateTime> lastLockoutDate { get; set; }
        public Nullable<System.DateTime> lastActivityDate { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> lastPasswordChangedDate { get; set; }
        public string userName { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isLockedOut { get; set; }
        public Nullable<bool> isOnline { get; set; }
    }
}
